'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, '..', 'public/index.html'), 'utf8');
assert.ok(html.includes('/src/storyline-v2-northstar.js'));
assert.ok(!html.includes('/src/storyline-v2-client.js'));
assert.ok(!html.includes('/src/storyline-v2-browser-bridge.js'));
assert.ok(html.includes('Open Dracula'));
console.log('  ✓ V2 is the sole public browser entrypoint');
